@rem the first parameter is the version number like "1.0.0.1"
@rem the second parameter is the path e.g. ..\ServiceHost\bin\Release
@rem > generate_msi.cmd 7.0.0.0 ..\Thycotic.RabbitMq.Helper\bin\Debug
copy icon.ico %2
"C:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe" dir %2 -o Output\Autogenerated.wxs -ag -sfrags -suid -cg main_component_group -t add_service_install.xsl -sreg -scom -srd -template fragment -dr INSTALLLOCATION
"C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -nologo -ext WixUtilExtension -dInstallerVersion=%1 Output\AutoGenerated.wxs Product.wxs -out Output\ -arch x64
"C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -b %2 -ext WixUIExtension -ext WixUtilExtension -nologo Output\AutoGenerated.wixobj Output\Product.wixobj -out Output\Thycotic.RabbitMq.Helper.%1.msi