// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Thycotic.MemoryMq.Tests.Collections
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ConcurrentPriorityQueue")]
    public partial class ConcurrentPriorityQueueFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ConcurrentPriorityQueue.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ConcurrentPriorityQueue", "In order to avoid silly mistakes\r\nI want to be sure queue behaves properly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("An new queue should be empty")]
        public virtual void AnNewQueueShouldBeEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("An new queue should be empty", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.Then("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest should be" +
                    " empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("An empty queue should be empty")]
        public virtual void AnEmptyQueueShouldBeEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("An empty queue should be empty", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest should be" +
                    " empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding to empty queue and then fully emptying it")]
        public virtual void AddingToEmptyQueueAndThenFullyEmptyingIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding to empty queue and then fully emptying it", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("item 2 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("item 4 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("item 8 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest should be" +
                    " empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding to empty queue")]
        public virtual void AddingToEmptyQueue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding to empty queue", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.And("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("item 2 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("item 4 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("item 8 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"2 4 8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding to empty queue with priority")]
        public virtual void AddingToEmptyQueueWithPriority()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding to empty queue with priority", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.And("the scenario object ConcurrentPriorityQueue ConcurrentPriorityQueueTest is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("item 2 is priorty enqueued in the scenario object ConcurrentPriorityQueue Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("item 4 is priorty enqueued in the scenario object ConcurrentPriorityQueue Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("item 8 is priorty enqueued in the scenario object ConcurrentPriorityQueue Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"8 4 2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding and removing from queue")]
        public virtual void AddingAndRemovingFromQueue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding and removing from queue", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.And("item 2 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("item 4 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("item 8 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("item is dequeued in the scenario object ConcurrentPriorityQueue ConcurrentPriorit" +
                    "yQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"4 8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding to queue with priority")]
        public virtual void AddingToQueueWithPriority()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding to queue with priority", ((string[])(null)));
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
 testRunner.And("item 4 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("item 8 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("item 2 is priorty enqueued in the scenario object ConcurrentPriorityQueue Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"2 4 8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Removing from empty queue")]
        public virtual void RemovingFromEmptyQueue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Removing from empty queue", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Removing from queue with a single item")]
        public virtual void RemovingFromQueueWithASingleItem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Removing from queue with a single item", ((string[])(null)));
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("there exists an integer ConcurrentPriorityQueue stored in the scenario as Concurr" +
                    "entPriorityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.And("item 2 is enqueued in the scenario object ConcurrentPriorityQueue ConcurrentPrior" +
                    "ityQueueTest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.When("all items are dequeued from scenario object ConcurrentPriorityQueue ConcurrentPri" +
                    "orityQueueTest and stored in scenario object array ConcurrentPriorityQueueResult" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.Then("the string join of scenario object array ConcurrentPriorityQueueResults should be" +
                    " \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
