using Thycotic.InstallerGenerator.Core.MSI.WiX;
using Thycotic.InstallerGenerator.Core.Steps;
using Thycotic.InstallerGenerator.MSI.WiX;

namespace Thycotic.InstallerGenerator.Steps.Services
{
    public abstract class BaseServiceWiXMsiGeneratorRunbook : WiXMsiGeneratorRunbook
    {
        protected static string GetArtifactFileName(string artifactName, string version)
        {
            return string.Format("{0}.{1}.msi", artifactName, version);
        }

        protected BaseServiceWiXMsiGeneratorRunbook(string recipePath, string sourcePath, string artifactName,
            string version)
        {

            RecipePath = recipePath;
            SourcePath = sourcePath;
            ArtifactName = artifactName;

            Steps = new IInstallerGeneratorStep[]
            {
                new ExternalProcessInstallerGeneratorStep
                {
                    Name = "Heat process",
                    WorkingPath = WorkingPath,
                    ExecutablePath = ToolPaths.Heat,
                    Parameters = string.Format(@"
dir {0}
-nologo
-o output\Autogenerated.wxs 
-ag 
-sfrags 
-suid 
-cg main_component_group 
-t add_service_install.xsl 
-sreg 
-scom 
-srd 
-template fragment 
-dr INSTALLLOCATION", sourcePath)

                },
                new ExternalProcessInstallerGeneratorStep
                {
                    Name = "Candle process",
                    WorkingPath = WorkingPath,
                    ExecutablePath = ToolPaths.Candle,
                    Parameters = string.Format(@"
-nologo 
-ext WixUtilExtension 
-dInstallerVersion={0} 
-out output\
output\AutoGenerated.wxs Product.wxs", version)
                },
                new ExternalProcessInstallerGeneratorStep
                {
                    Name = "Light process",
                    WorkingPath = WorkingPath,
                    ExecutablePath = ToolPaths.Light,
                    Parameters = string.Format(@"
-nologo
-b {0}
-ext WixUIExtension 
-ext WixUtilExtension 
-out {1}
output\AutoGenerated.wixobj output\Product.wixobj", sourcePath, artifactName)
                }
            };
        }
    }
}
